name: Build AdsPlay Apps
on: [push, workflow_dispatch]

jobs:
  build:
    name: Build Apps
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4 # Cập nhật lên v4

      - name: Setup Java
        uses: actions/setup-java@v4 # Cập nhật lên v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Build Windows
        run: |
          flutter config --enable-windows-desktop
          flutter build windows --release

      - name: Upload Results
        uses: actions/upload-artifact@v4 # ĐÂY LÀ CHỖ SỬA QUAN TRỌNG NHẤT
        with:
          name: AdsPlay-Release-Files
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/windows/runner/Release/
