name: Build Old AdsPlay
on: [push, workflow_dispatch]

jobs:
  build:
    name: Build Process
    runs-on: windows-latest
    
    # ĐÂY LÀ PHẦN QUAN TRỌNG NHẤT: Chỉ đường vào thư mục chứa code
    defaults:
      run:
        working-directory: adsplay

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.5'
          channel: 'stable'

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Android
        run: flutter build apk --release --no-sound-null-safety

      - name: Build Windows
        run: |
          flutter config --enable-windows-desktop
          flutter build windows --release --no-sound-null-safety

      - name: Save Results
        uses: actions/upload-artifact@v4
        with:
          name: App-Ready-To-Use
          path: |
            adsplay/build/app/outputs/flutter-apk/app-release.apk
            adsplay/build/windows/runner/Release/
