name: Mobile and Desktop Packaging
on: [push, workflow_dispatch]

jobs:
  build:
    name: Build Process
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0' # Ép dùng bản cũ để khớp với code
          channel: 'stable'

      - name: Get Dependencies
        run: |
          flutter pub get # Không dùng upgrade nữa để giữ nguyên bản gốc của tác giả

      - name: Build Android
        # Thêm --no-sound-null-safety nếu code quá cũ
        run: flutter build apk --release --no-sound-null-safety 

      - name: Build Windows
        run: |
          flutter config --enable-windows-desktop
          flutter build windows --release

      - name: Save Results
        uses: actions/upload-artifact@v4
        with:
          name: App-Files-Ready
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/windows/runner/Release/
